### ISSUE TITLE
First step. Loopback intro

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-10#2]
## intro
https://github.com/optis/loopback-rest-api - this is the best tutorial that helps me 1 year ago.

Please buzz me before including MongoDB database - so I'll generate a new instance for you.

As I want to see your progress - please use this repo and push your progress here. Share with me progress and questions that I can help you with. Don't hesitate to use my help. i willing to start fast and with less stress for you at the beginning. Also will check your git skills.

## Is there any timeline to finish?
nope, because you only starting this. and I know how hard it can be from
the beginning. But this is the best tutorial that I find about loopback. I
use it too a year ago.
btw, as usually - feel free and ask any questions or seek my help here.

# invite link
Please use this link in order to be added as a contributor: https://github.com/ChickenKyiv/loopback-tutor-intern-10/invitations

**Comment by atherdon** [comment]
i created a mongodb instance for you. it's here: #4

**Comment by louisevdb84** [comment]
Not sure what I closed just now
