### ISSUE TITLE
clean up task

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-10#23]
can you do this, please?
https://github.com/GroceriStar/groceristar/issues/508
https://github.com/ChickenKyiv/recipe-api-only/issues/202
https://github.com/ChickenKyiv/recipe-search-api/issues/28

**Comment by louisevdb84** [comment]
Cool, will have a look tomorrow

**Comment by louisevdb84** [comment]
Done.  The only thing i did on all 3 of them was running npm uninstall mocha command. if there is anything else i need to do regarding this task, please let me know

**Comment by atherdon** [comment]
no, that it. just received an update for mocha package few days before,
but as we moving from mocha to jest(because it used at React and also
backed by Facebook) we don't need it for API too


On 25-May-2018 at 10:00 AM, Louise wrote:


Done. The only thing i did on all 3 of them was running npm uninstall mocha
command. if there is anything else i need to do regarding this task, please
let me know

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChickenKyiv/loopback-tutor-intern-10/issues/23#issuecomment-392004924>,
or mute the thread
