### ISSUE TITLE
raven/sentry configuration

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-10#3]
`Raven.config('https://77aa2ee9a7ce484497f56278982a0809@sentry.io/305339').install()`

Init:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L17

How to use this tracer:
https://github.com/GroceriStar/groceristar/blob/master/server/server.js#L60

if you'll cover your code well with this tracer - when you'll break something - I'll receive an email notification and will be able to understand more clearly what was goes wrong.

![image](https://user-images.githubusercontent.com/1469198/37542679-b443d8f0-2967-11e8-8d98-7fc3e9aabe6b.png)

**Comment by louisevdb84** [comment]
I added a try catch block with Raven in all the .js files.  It is part of the pull request now.  Please let me know if you only wanted it in the server.js file, then I will remove it from all the other files.

**Comment by atherdon** [comment]
for this moment i want just install it + configure. it'll be a great feature later for you, when you'll work with custom remote methods - because with this thing it'll be easy to debug and catch errors when you crash something.

**Comment by atherdon** [comment]
you can add another `try - catch` block here : https://github.com/ChickenKyiv/loopback-tutor-intern-10/blob/master/server/models/reservation.js#L13
and this will be one of situations where you check errors inside model methods.
closing this task - well done!
