### ISSUE TITLE
mongodb link

### ISSUE THREAD

**Issue by atherdon** [ChickenKyiv/loopback-tutor-intern-10#4]
mongodb://heroku_b05c1rpf:jl8t2p304u5eokkphv0fof57r9@ds153948.mlab.com:53948/heroku_b05c1rpf

You'll need to have a loopback-connector-mongo package in order to setup it well.

Sample: https://github.com/GroceriStar/groceristar/blob/master/server/datasources.json

**Comment by louisevdb84** [comment]
Added the link in the code as per example. Should form part of the pull request.
